//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tud.mci.tangram.TangramLector.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tud.mci.tangram.TangramLector.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;mappings&gt;
        ///  &lt;!--
        ///  &lt;function name=&quot;callMeFunction&quot; description=&quot;some function to handle something&quot;&gt;
        ///    &lt;mapping device=&quot;_default&quot;&gt;f1,f2, fn3, gesture,none,unknown,&lt;/mapping&gt;
        ///    &lt;mapping device=&quot;BrailleDis&quot;&gt;k1,k2,k3&lt;/mapping&gt;
        ///  &lt;/function&gt;
        ///  --&gt;
        ///
        ///  &lt;!-- General Commands --&gt;
        ///
        ///  &lt;function name=&quot;abortSpeechOutput&quot; description=&quot;Aborts all audio feedback immediately&quot;&gt;
        ///    &lt;mapping device=&quot;_default&quot;&gt;F1&lt;/mapping&gt;
        ///  &lt;/function&gt;
        ///  
        ///  &lt;function name=&quot;recalibrat [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string GlobalFunctionMappings {
            get {
                return ResourceManager.GetString("GlobalFunctionMappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot; standalone=&quot;yes&quot; ?&gt;
        ///&lt;localization&gt;
        ///
        ///  &lt;locale language=&quot;default&quot;&gt;
        ///    &lt;trans id=&quot;tangram.lector.not&quot;&gt;not&lt;/trans&gt;
        ///
        ///    &lt;trans id=&quot;tangram.lector.&quot;&gt;&lt;/trans&gt;
        ///
        ///    &lt;trans id=&quot;tangram.lector.oo_observer.selected_no&quot;&gt;No element selected.&lt;/trans&gt;
        ///    &lt;trans id=&quot;tangram.lector.oo_observer.selected&quot;&gt;{0} selected.&lt;/trans&gt;
        ///    &lt;trans id=&quot;tangram.lector.oo_observer.selected_element&quot;&gt;{0} element selected.&lt;/trans&gt;
        ///    &lt;trans id=&quot;tangram.lector.oo_observer.selected_elements [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Byte[].
        /// </summary>
        internal static byte[] unicode {
            get {
                object obj = ResourceManager.GetObject("unicode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
